In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../data/raw/meteo_departements_senegal_2021_2026.csv')
print(df.head())

         DRS      DISTRICT       PERIODE  temperature_moyenne  \
0  DRS Dakar  Dakar Centre  Janvier 2021                21.04
1  DRS Dakar  Dakar Centre  Février 2021                19.87
2  DRS Dakar  Dakar Centre     Mars 2021                19.75
3  DRS Dakar  Dakar Centre    Avril 2021                20.20
4  DRS Dakar  Dakar Centre      Mai 2021                21.00

   temperature_max  temperature_min  precipitation  humidite  vent  \
0            23.28            19.53           0.06     71.73  5.40
1            22.08            18.72           1.68     78.41  5.11
2            21.10            18.93           8.03     84.41  5.43
3            21.21            19.62           0.39     89.08  4.79
4            21.63            20.55           0.97     89.98  4.55

   rayonnement_solaire
0                 5.13
1                 5.25
2                 6.81
3                 7.11
4                 6.59

In [4]:
# Convert French month names to English
month_map = {
    "Janvier": "January",
    "Février": "February",
    "Mars": "March",
    "Avril": "April",
    "Mai": "May",
    "Juin": "June",
    "Juillet": "July",
    "Août": "August",
    "Septembre": "September",
    "Octobre": "October",
    "Novembre": "November",
    "Décembre": "December"
}

# Replace French month names
for fr, en in month_map.items():
    df["PERIODE"] = df["PERIODE"].str.replace(fr, en, regex=False)

# Convert to datetime
df["PERIODE"] = pd.to_datetime(df["PERIODE"], format="%B %Y")

# Split the data from 2021 to 2024 for training and 2025 for test to 2026 for remaining data
train_df = df[df["PERIODE"].dt.year.isin([2021, 2022, 2023, 2024])]
test_df = df[df["PERIODE"].dt.year.isin([2025])]
test_remain = df[df["PERIODE"].dt.year.isin([2026])]

print("Training shape:", train_df.shape)
print("Test shape:", test_df.shape)
print("Remaining test shape:", test_remain.shape)

Training shape: (3792, 10)
Test shape: (948, 10)
Remaining test shape: (632, 10)

In [5]:
# Save if needed
train_df.to_csv("../../data/raw/meteo_departements_senegal_2021_2024_train.csv", index=False)
test_df.to_csv("../../data/raw/meteo_departements_senegal_2025_test.csv", index=False)
test_remain.to_csv("../../data/raw/meteo_departements_senegal_2026_test_remain.csv", index=False)

Add weather value to processed

In [6]:
# Read data in ../../data/processed/Base_PEC_MALARIA_CS_2021_2024.xlsx
df_processed = pd.read_excel('../../data/raw/Base_PEC_MALARIA_CS_2021_2024.xlsx')

# Replace French month names
for fr, en in month_map.items():
    df_processed["PERIODE"] = df_processed["PERIODE"].str.replace(fr, en, regex=False)

# Convert to datetime
df_processed["PERIODE"] = pd.to_datetime(df_processed["PERIODE"], format="%B %Y")


df_processed.head()

,DRS,DISTRICT,PERIODE,Est ce que vous avez connu plus de 7 jours de rupture consecutifs ACT petit enfant?,Palu:Primaquine-Stock reçu,Case de santé ayant notifié,R23_DSME_Premier contact CPN8,Traitements ACT dispensés à Petit Enfant (1 à 5 ans),Est ce que vous avez connu plus de 7 jours de rupture consecutifs ACT adulte?,Palu:ACT NRSS-Stock reçu,...,Nombre de sites PECADOM fonctionnels,Palu:ACT adulte-Traitement Dispensé,Palu:ACT petit enfant-Traitement Dispensé,PALU - FS avec stock MILDA,Cas Suspect Palu hospitalisations,Palu:Quinine 200-Nombre jours de rupture,Palu:ACT adulte-Nombre jours de rupture consecutif,Nombre total de cas de paludisme GRAVE confirmes par TDR ou GE,Goutte Epaisse réalisés [Positifs + Négatifs] palu,Est ce que vous avez connu plus de 7 jours de rupture consecutifs Quinine 200?
0,DRS Tambacounda,Bakel,2021-01-01,0.0,NaN,8.0,NaN,1.0,0.0,NaN,...,40.0,14.0,1.0,NaN,14.0,NaN,NaN,NaN,NaN,NaN
1,DRS Tambacounda,Bakel,2021-02-01,0.0,NaN,8.0,NaN,NaN,0.0,42.0,...,40.0,5.0,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN
2,DRS Tambacounda,Bakel,2021-03-01,1.0,NaN,7.0,NaN,NaN,0.0,NaN,...,40.0,1.0,1.0,NaN,20.0,NaN,NaN,NaN,NaN,NaN
3,DRS Tambacounda,Bakel,2021-04-01,0.0,NaN,8.0,NaN,NaN,0.0,5.0,...,40.0,NaN,NaN,NaN,31.0,NaN,NaN,NaN,NaN,NaN
4,DRS Tambacounda,Bakel,2021-05-01,0.0,NaN,8.0,NaN,NaN,0.0,50.0,...,41.0,NaN,NaN,NaN,21.0,NaN,75.0,NaN,NaN,NaN

In [7]:
train_df.head()

,DRS,DISTRICT,PERIODE,temperature_moyenne,temperature_max,temperature_min,precipitation,humidite,vent,rayonnement_solaire
0,DRS Dakar,Dakar Centre,2021-01-01,21.04,23.28,19.53,0.06,71.73,5.40,5.13
1,DRS Dakar,Dakar Centre,2021-02-01,19.87,22.08,18.72,1.68,78.41,5.11,5.25
2,DRS Dakar,Dakar Centre,2021-03-01,19.75,21.10,18.93,8.03,84.41,5.43,6.81
3,DRS Dakar,Dakar Centre,2021-04-01,20.20,21.21,19.62,0.39,89.08,4.79,7.11
4,DRS Dakar,Dakar Centre,2021-05-01,21.00,21.63,20.55,0.97,89.98,4.55,6.59

In [8]:
# Insert train_df to df_processed before R20_DSME_Femmes enceintes ayant reçu TPI 2 column where DRS, PERIODE and DEPARTEMENT match
# Merge on the matching keys
merged_df = df_processed.merge(
    train_df,
    on=["DRS", "PERIODE", "DISTRICT"],
    how="left"
)

# Columns to insert (exclude the key columns)
new_cols = [
    col for col in train_df.columns
    if col not in ["DRS", "PERIODE", "DISTRICT"]
]

# Find insertion position
insert_pos = merged_df.columns.get_loc("R20_DSME_Femmes enceintes ayant reçu TPI 2")

# Reorder columns
cols = (
    list(merged_df.columns[:insert_pos])
    + new_cols
    + [c for c in merged_df.columns[insert_pos:] if c not in new_cols]
)

merged_df = merged_df[cols]

In [9]:
# Save the merged DataFrame to a new Excel file
merged_df.to_excel('../../data/features/Base_MALARIA_CS_CLEAN_2021_2024_with_weather_2.xlsx', index=False)